Fallback to delete directly from buildpack (#4)
* If no buildpack-run.sh found in slug, then fallback to deleting node_modules direclty from this buildpack.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -25,5 +25,27 @@ if [ -f $BUILDPACK_RUN_FILE ]; then
 
   printf "...Done!\n"
 else
-  printf "${RED}Fail:${NO_COLOR} Unable to run Node Modules Cleanup script.\n"
+  # Attempt to clean node_modules directly from this buildpack.
+  if [ -f $BUILD_DIR/package.json ]; then
+    cd "$BUILD_DIR" || exit
+
+    echo "-----> Deleting node_modules/@babel..."
+    rm -rf node_modules/@babel
+
+    echo "-----> Deleting node_modules/@gusto/workbench-illos..."
+    rm -rf node_modules/@gusto/workbench-illos
+
+    echo "-----> Deleting node_modules/.cache..."
+    rm -rf node_modules/.cache
+
+    echo "-----> Deleting node_modules/flowgen..."
+    rm -rf node_modules/flowgen
+
+    echo "-----> Deleting node_modules/typescript..."
+    rm -rf node_modules/typescript
+
+    echo "-----> Finished nuking unnecessarily large node_modules folders!"
+  else
+    printf "${RED}Fail:${NO_COLOR} Unable to run Node Modules Cleanup script.\n"
+  fi
 fi
diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -14,12 +14,20 @@ RED='\033[0;31m'
 
 # Check if buildpack-run.sh file exists to ensure we can run the proper scripts
 
-MESSAGE="Node Modules Cleanup\n"
+MESSAGE="Node Modules Cleanup:"
+FAIL_PREFIX="${RED}Fail:${NO_COLOR}"
 
 if [ ! -f $BUILDPACK_RUN_FILE ]; then
-  FAIL_PREFIX="${RED}Fail:${NO_COLOR}"
+  if [ -f $BUILD_DIR/package.json ]; then
+    echo "$MESSAGE"
+    echo "-----> Cannot find buildpack-run.sh in slug. Attempting original version of node_modules cleanup..."
+    exit 0
+  else
+    echo "$MESSAGE"
+    printf "-----> ${FAIL_PREFIX} Cannot find buildpack-run.sh in slug, or attempt node_modules cleanup."
+    exit 1
+  fi
+else
+  echo "${MESSAGE}"
+  exit 0
 fi
-
-printf "${FAIL_PREFIX} ${MESSAGE}"
-
-exit 0
