If no buildpack-run.sh found in slug, then fallback to deleting node_modules direclty from this buildpack.

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -15,11 +15,18 @@ RED='\033[0;31m'
 # Check if buildpack-run.sh file exists to ensure we can run the proper scripts
 
 MESSAGE="Node Modules Cleanup\n"
+FAIL_PREFIX="${RED}Fail:${NO_COLOR}"
 
 if [ ! -f $BUILDPACK_RUN_FILE ]; then
-  FAIL_PREFIX="${RED}Fail:${NO_COLOR}"
+  if [ -f $BUILD_DIR/package.json ]; then
+      echo MESSAGE
+      echo "Cannot find buildpack-run.sh in mithin repo. Attempting original version of node_modules cleanup..."
+      exit 0
+  fi
+
+  printf "${FAIL_PREFIX} ${MESSAGE}"
+  exit 1
 fi
 
-printf "${FAIL_PREFIX} ${MESSAGE}"
-
+printf "${MESSAGE}"
 exit 0
